[package]
name = "settlement"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared" }
ethcontract = { workspace = true }
primitive-types = { workspace = true }

[lints]
workspace = true