[package]
name = "contracts"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
utils = { path = "../utils" }
alloy = "1.0.12"
ethcontract = "0.25.8"
web3 = "0.19.0"
serde = { version = "1.0.219", features = ["derive"] }
anyhow = "1.0.98"
tokio = "1.45.1"
