[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
# Add dependencies as needed

# Utils dependencies
shared = { path = "../shared" }
serde = { version = "1.0.219", features = ["derive"] }
hex = "0.4.3"
tiny-keccak = "2.0.2"
anyhow = "1.0.98"

